name = "fase"
description = "cw"
version = "0.1.0-dev"

authors = ["jamie young"]
maintainers = ["jamie young <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["fase"]
